spring.application.name=app
server.port=8081
management.endpoints.web.exposure.include=shutdown

spring.r2dbc.url=r2dbc:mysql://localhost:3306/db_app_restfulapi_springboot
spring.r2dbc.username=root
spring.r2dbc.password=

# spring.datasource.initialization-mode=always
# spring.datasource.schema=classpath:schema.sql
# spring.datasource.data=classpath:data.sql